# -*- coding: utf-8 -*-
"""AI_custom_selection_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WOnIyrkfsnciozVjcwjfWc3qXZx7SH4h
"""

model_choice = int((input(" 0: LinearRegression\n 1: DecisionTreeRegressor\n 2: LogisticRegression\n 3: DecisionTreeClassifier\n 4: PolynomialRegression\n ")))

if(model_choice == 4) :
  chosen_degree = int(input("enter the degree of the polynomial\n"))

dataset_choice = int((input(" 0: iris\n 1: breast_cancer\n 2: diabetes\n ")))

if( model_choice < 2 or model_choice==4 ) :
  score_choice = int((input(" 0: mean_absolute_error\n 1: mean_squared_error\n 2: r2_score\n ")))
else :
  score_choice = int((input(" 0: accuracy_score\n 1: precision_score\n 2: recall_score\n ")))

from sklearn.datasets import load_iris, load_breast_cancer, load_diabetes

d_sets = [ load_iris, load_breast_cancer, load_diabetes ]
dataset = d_sets[dataset_choice]()

X = dataset.data
y = dataset.target

if( model_choice == 4 ) :
      from sklearn.preprocessing import PolynomialFeatures
      pf = PolynomialFeatures(degree = chosen_degree)
      X = pf.fit_transform( X )

from sklearn.model_selection import train_test_split

#x_train, x_test, y_train, y_test = train_test_split(X, y, split_size=0.3)
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier

if( model_choice<4 ) :
  m_set = [ LinearRegression, DecisionTreeRegressor, LogisticRegression, DecisionTreeClassifier ]
  model = m_set[model_choice]()
else :
  model = LinearRegression()

model.fit( x_train, y_train )

y_pred = model.predict(x_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score, precision_score, recall_score

if( model_choice < 2 or model_choice==4 ) :
  s_set = [ mean_absolute_error, mean_squared_error, r2_score ]
else :
  s_set = [ accuracy_score, precision_score, recall_score ]

score = s_set[score_choice](y_pred, y_test)

if s_set[score_choice] in [precision_score, recall_score]:
  score = s_set[score_choice](y_pred, y_test, average='weighted')
else:
  score = s_set[score_choice](y_pred, y_test)

print(f"score obtained = {score} ")